<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $this->getPageTitle("|") ?> Microframework</title>
    <link rel="stylesheet" href="/assets/css/style.css">
    <link rel="stylesheet" href="/assets/css/login.css">
    <script src="https://kit.fontawesome.com/84028ed802.js" crossorigin="anonymous"></script>

</head>
<body class="">
    <?php $this->loadView('Alerts/_success'); ?>
    <?php $this->loadView('Alerts/_errors'); ?>
    <div class="text-center body">
      
      <form class="form-signin" method="POST" action="/register">
        <h1>Cadastre-se</h1>
        <label for="nome" class="sr-only">Nome</label>
        <input 
          type="text" 
          id="nome" 
          name="nome" 
          class="form-control mb-3" 
          placeholder="Nome" 
          required="" 
          autofocus=""
        >
        <label for="email" class="sr-only">Email</label>
        <input 
          type="text" 
          id="email" 
          name="email" 
          class="form-control mb-3" 
          placeholder="Email" 
          required="" 
          autofocus=""
        >
        
        <label for="password" class="sr-only">Senha</label>
        <input 
          type="password" 
          id="password"
          name="password" 
          class="form-control mb-3" 
          placeholder="Senha" 
          required=""
          >
        <button class="btn btn-lg btn-primary btn-block" type="submit">Cadastrar</button>
      </form>
    </div>
</body>
