<div class="container">
    <h1 class="h1">
        <?=  $this->getPageTitle(); ?>
        <a class="btn btn-primary float-right" href="/posts/create">
            <i class="fas fa-plus"></i> Novo Post
        </a>
    </h1>
    <?php $this->loadView('Alerts/_success'); ?>
    <?php $this->loadView('Alerts/_errors'); ?>
    <?php  foreach ($this->view->posts as $post): ?>
    <div class="border p-2 mb-2">
        <h3 class="h3"><a class="nav-link" href="/posts/<?= $post->id;?>/show"><?php echo $post->titulo; ?></a> </h3>
        <p class="text-justify"><?= $post->conteudo; ?> </p>
        <p class="text-right">
            <a href="/posts/<?= $post->id; ?>/edit" class="btn btn-info btn-sm">
                <i class="fas fa-edit"></i>
            </a>
            <a href="/posts/<?= $post->id; ?>/delete" class="btn btn-outline-danger btn-sm" onclick="return confirm('Deseja deletar este post?');">
                <i class="fas fa-trash"></i>
            </a>
        </p>
    </div>
    <?php endforeach; ?>
</div>